name: BuildAndTest

on:
  push:
    branches: [ "main" ]
    tags:        
      - '*'           # Push events to every tag not containing /
  pull_request:
    branches: [ "main" ]

jobs:

  buildAndPublish:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.2.0
        with:
          versionSpec: '6.4.x'
      - name: Determine Version
        id: version_step # step id used as a reference for output values
        uses: gittools/actions/gitversion/execute@v4.2.0
      - name: Update Project File
        uses: gittools/actions/gitversion/execute@v4.2.0
        with:
          updateProjectFiles: true
      - name: Install dependencies
        run: dotnet restore ./DemoApp/WebApplication1/WebApplication1.csproj
      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore ./DemoApp/WebApplication1/WebApplication1.csproj
      - name: Publish
        run: dotnet publish -c Release --output ./Release ./DemoApp/WebApplication1/WebApplication1.csproj
      - name: Zip Folder
        run: |
          cd ./Release
          zip -r Testversion_${{ env.GitVersion_majorMinorPatch }}.zip * -x ".git/*" ".github/*" "appsettings.Development.json"
      - uses: actions/upload-artifact@v4
        with:
          name: Testversion_${{ steps.version_step.outputs.majorMinorPatch }}
          path: ./Release/Testversion_${{ env.GitVersion_majorMinorPatch }}.zip
      - uses: softprops/action-gh-release@v2
        name: Release
        if: github.ref_type == 'tag'
        with:
          files: ./Release/Testversion_${{ env.GitVersion_majorMinorPatch }}.zip
          
      
